### PR TITLE
Add support for OpportunitiyStatus and ContactApi

### PR DESCRIPTION
**Pull request by wridgers**
Based on existing support for LeadStatus.

### CODE REVIEW

**Comment by wridgers** [comment]
Sorry, I should have made a feature branch.

I will stop committing now. I am using this in production and it's working well for me.

Any change it can be merged in?

**Comment by null9beta** [comment]
@wridgers we will take care of your PullRequest soon. In this case you can actually just keep that PullRequest into develop open. You are right, typically we will go into a feature branch first but we reviewed you changes briefly and it looks quite good. 

Is there more changes from your side we shall wait before we review the PR ?

**Comment by wridgers** [comment]
@null9beta I don't think I will be making any more changes right now so you can proceed. :) Thanks.

**Comment by marczahn** [comment]
@wridgers Thank you very much for your work!

**Comment by wridgers** [comment]
Great, thanks! :)

**Pull request merged**
