### PR TITLE
refs #43: fix coveralls path

### LINKED ISSUE #43: Fix coverall that can't check the source coverage

### PR DESCRIPTION
**Pull request by mavimo**
Closes #43

### CODE REVIEW

**Comment by mavimo** [comment]
@mickadoo it sto to work some years ago (last build tracked on coveralls is from 19 JAN 2015 ) I'm experimenting on how to re-enable it and and add webhook to indicate the coverage changes for each PR.

**Comment by mavimo** [comment]
@mickadoo can you enable PR coverage report as reported on http://docs.coveralls.io/coveralls-notifications ? I've not access to the notification tab on coveralls

**Comment by mickadoo** [comment]
@mavimo what notifications would you like? 

I think that link you sent is a bit dated and I see different settings:

image

There are also email notification settings

image

**Comment by mavimo** [comment]
Seems coveralls drop support for comments on PRs (is active on settings but not reported on comments, sorry)

**Pull request merged**
