### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by EnoahNetzach**

### CODE REVIEW

**Comment by mickadoo** [comment]
@EnoahNetzach Are these fixed versions causing some problem for you? I can see the point in changing it to include bugfixes with the `^` but I don't think the `>=` is a good option since it could include breaking changes with major versions.

**Comment by EnoahNetzach** [comment]
You are right, for the moment it causes no problems, I'll fix it. ;)

**Comment by EnoahNetzach** [comment]
*too strict, damn it

**Comment by mickadoo** [comment]
@EnoahNetzach Merged. Thanks for the help

**Pull request merged**
